# **Introduction to NumPy**

![alt text](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSMrTWz33b86nfIrgaW9jE_t-7VCcqJtjL-pg&s)


A NumPy array is a powerful data structure in Python provided by the NumPy (Numerical Python) library. It is a grid of values, all of the same type, indexed by a tuple of non-negative integers. Arrays in NumPy are a more efficient and flexible way of storing and manipulating large datasets compared to Python's native lists. They provide support for mathematical operations on arrays, such as element-wise addition, subtraction, multiplication, and division, and offer a range of functions for working with large datasets.

## **Key Features of NumPy Arrays**

- **Efficient storage and operations:** NumPy arrays use less memory and provide faster data processing compared to lists.
- **Homogeneous data types:** All elements of a NumPy array must be of the same data type.
- **Multi-dimensional arrays:** NumPy supports 1D, 2D, and n-dimensional arrays, allowing complex data manipulation.
- **Broadcasting:** Operations on arrays of different shapes can be carried out using a technique called broadcasting.
- **Support for a wide range of functions:** It includes mathematical, logical, linear algebra, Fourier transform, and random number generation functions.

![alt text](https://miro.medium.com/v2/resize:fit:828/1*kM5rQZIpBAjbs7UkqUWJdg.jpeg)

## **Numpy Array Data Type Precedence**

NumPy automatically determines the data type of an array based on the types of the elements in the array. When elements of different data types are combined in an array, NumPy applies data type precedence to convert the elements to a common type. The precedence follows a hierarchy where more general types can encompass less general ones.

Here is the general order of NumPy data type precedence (from lowest to highest precision):

1. Boolean (bool)
2. Integer (int)
3. Unsigned Integer (uint)
4. Float (float)
5. Complex (complex)
6. String (str)
7. Object (object)

 
## **NumPy Matrix**
 
Numpy means Numerical Python. The Numpy matrix is a package in Python which is the core scientific computing library. It contains a powerful n-dimensional array object and also enables integrations of C and C++.

The Numpy matrix has a number of uses; from linear algebra to random number capability to its use as a container for generic data.


## **Why use NumPy?**

NumPy gives you an enormous range of fast and efficient ways of creating arrays and manipulating numerical data inside them. While a Python list can contain different data types within a single list, all of the elements in a NumPy array should be homogeneous. The mathematical operations that are meant to be performed on arrays would be extremely inefficient if the arrays weren’t homogeneous.


NumPy arrays are faster and more compact than Python lists. An array consumes less memory and is convenient to use. NumPy uses much less memory to store data and it provides a mechanism of specifying the data types. This allows the code to be optimized even further.

## **NumPy Installation**
 
All you need to do is type “**pip install numpy**” in the command prompt. This starts the installation. As soon as Numpy is installed go to the **IDE(Integrated Development Environment)** and then import Numpy by typing “**import numpy as np**”.
 
## **NumPy Array**
 
A Numpy Array or Numpy matrix is a two-dimensional array that contains both rows and columns. Here’s an example of a NumPy array that has 4 columns and 3 rows.

![numpy array.png](https://miro.medium.com/v2/resize:fit:817/0*y04Nh3L0aSwyGaby.png)

**Single Dimensional Numpy Matrix:**



In [1]:
my_list = [1, 2, 3, 4]
print(type(my_list))

my_dict = {"name": "ravi"}
print(type(my_dict))

<class 'list'>
<class 'dict'>


In [1]:
import numpy
print(numpy.__version__)

2.1.1


In [3]:
import numpy

mat = numpy.array([1, 2, 3, 4])
print(type(mat))
print(mat)

<class 'numpy.ndarray'>
[1 2 3 4]


NumPy’s main object is the **homogeneous multidimensional array**. It is a table of elements (usually numbers), all of the same type, indexed by a tuple of non-negative integers. In NumPy dimensions are called **axes**.

For example, the coordinates of a point in 3D space **[1, 2, 1]** has one axis. That axis has 3 elements in it, so we say it has a length of 3. In the example below, the array has 2 axes. The first axis has a length of 2, the second axis has a length of 3.

```
[[ 1., 0., 0.],
 [ 0., 1., 2.]]
```

**NumPy’s array class is called ndarray**. It is also known by the alias array. Note that **numpy.array** is not the same as the Standard Python Library class **array.array**, which **only handles one-dimensional arrays** and offers less functionality.

**Multi Dimensional Numpy Matrix:**

In [9]:
import numpy as np  # aliasing

mat1 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(type(mat1))

<class 'numpy.ndarray'>


In [5]:
"""
Now let's have a look at the type of mat and mat1
what it will be????
"""
print(type(mat), type(mat1))

<class 'numpy.ndarray'> <class 'numpy.ndarray'>


In [6]:
np.array([
    [1, 2, 3, 4, 5], 
    [1, 2, 3, 4, 5]
])

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [2]:
# basic
import numpy as np

arr = [1,2,3,4,5,6,7,8]
arr[2:5] = [10,11,12]
print(arr)

sub_list = arr[5:]
sub_list = [13,14,15]
print(arr,end='\n\n')

# now making it an nympy array
arr = np.arange(9)  
print(arr)

sub_list = arr[2:5]
sub_list[:] = [10,11,12]   # the sub_list is pointing to the 2:5 memory portion of the arr and change is thus reflected in orignal arr
arr

[1, 2, 10, 11, 12, 6, 7, 8]
[1, 2, 10, 11, 12, 6, 7, 8]

[0 1 2 3 4 5 6 7 8]


array([ 0,  1, 10, 11, 12,  5,  6,  7,  8])

## **Fancy Indexing**

In this example, we demonstrate how to create a 2D array using NumPy, fill it with values, and access specific rows of the array using advanced indexing.

### Code Example

```python
# Access specific rows of the array using advanced indexing
# Access rows 4, 3, -2 (second last), and -1 (last row)
result = arr[[4, 3, -2, -1]]
print("Selected Rows:\n", result)
# we have to pass a list inside the [ ]

In [10]:
arr = np.zeros((8,4),dtype="int8") 

for i in range(1,8):
    arr[i] = i 

print(arr)

arr[[4,3,-2,-1]]   # pass index 

[[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]
 [5 5 5 5]
 [6 6 6 6]
 [7 7 7 7]]


array([[4, 4, 4, 4],
       [3, 3, 3, 3],
       [6, 6, 6, 6],
       [7, 7, 7, 7]], dtype=int8)

As you can see both instances belongs to **numpy.ndarray** class, where ndarray simply stands for **n-dimensional array**.

## **Attributes of Numpy Array**

The more important attributes of an ndarray object are:
 
- **ndarray.ndim**

the number of axes (dimensions) of the array.

- **ndarray.shape**

the dimensions of the array. This is a tuple of integers indicating the size of the array in each dimension. For a matrix with n rows and m columns, the shape will be (n,m). The length of the shape tuple is therefore the number of axes, ndim.

- **ndarray.size**

the total number of elements of the array. This is equal to the product of the elements of shape.

- **ndarray.dtype**

an object describing the type of the elements in the array. One can create or specify dtype using standard Python types. Additionally NumPy provides types of its own. **numpy.int32, numpy.int16, and numpy.float64** are some examples.

- **ndarray.itemsize**

the size in bytes of each element of the array. For example, an array of elements of type float64 has itemsize 8 (=64/8), while one of type complex32 has itemsize 4 (=32/8). It is equivalent to **ndarray.dtype.itemsize**.


Let's jump into examples for everything to understand things in better way...

**1. ndarray.ndim**

In [7]:
import numpy as np

def give_dimension(my_mat):
    print("dimension = ", my_mat.ndim)

give_dimension(np.array([1, 2, 3, 4, 5]))
give_dimension(np.array([[1, 2, 3, 4, 5], [5, 6, 7, 8, 9]]))
give_dimension(
    np.array(
        [
            [[0, 1, 2], [3, 4, 5], [6, 7, 8]],
            [[9, 10, 11], [12, 13, 14], [15, 16, 17]],
            [[18, 19, 20], [21, 22, 23], [24, 25, 26]],
        ]
    )
)

dimension =  1
dimension =  2
dimension =  3


**2. ndarray.shape**

In [13]:
import numpy as np

def get_shape(my_mat):
    print("(shape/order) = ", my_mat.shape)

get_shape(np.array([1, 2, 3, 4, 5]))
# list of lists
get_shape(np.array(
    [
        [1, 2, 3, 4, 5], 
        [5, 6, 7, 8, 9]
    ]
))
get_shape(
    np.array(
        [
            [[0, 1, 2], [3, 4, 5], [6, 7, 8]],
            [[9, 10, 11], [12, 13, 14], [15, 16, 17]],
            [[18, 19, 20], [21, 22, 23], [24, 25, 26]],
        ]
    )
)

(shape/order) =  (5,)
(shape/order) =  (2, 5)
(shape/order) =  (4, 3, 3)


**3. ndarray.size**

In [9]:
import numpy as np

def get_size(my_mat):
    print(f"(size/total number of elements) = ", my_mat.size)

get_size(np.array([1, 2, 3, 4, 5]))
get_size(np.array([[1, 2, 3, 4, 5], [5, 6, 7, 8, 9]]))
get_size(
    np.array(
        [
            [[0, 1, 2], [3, 4, 5], [6, 7, 8]],
            [[9, 10, 11], [12, 13, 14], [15, 16, 17]],
            [[18, 19, 20], [21, 22, 23], [24, 25, 26]],
        ]
    )
)

(size/total number of elements) =  5
(size/total number of elements) =  10
(size/total number of elements) =  27


**4. ndarray.dtype**

In [10]:
import numpy as np

def data_type(my_matrix):
    print("data type: ", my_matrix.dtype)

data_type(np.array([1.34, 2.45, 1.35, 7.69, 8.56]))
data_type(np.array([4j, 4 + 3j, 6 - 9j]))
data_type(np.array(["a", "b", "c", "abc", "ravipande", "hiten"]))

data type:  float64
data type:  complex128
data type:  <U9


The Unicode Standard provides a unique number for every character, no matter what platform, device, application or language. It has been adopted by all modern software providers and now allows data to be transported through many different platforms, devices and applications without corruption. Support of Unicode forms the foundation for the representation of languages and symbols in all major operating systems, search engines, browsers, laptops, and smart phones—plus the Internet and World Wide Web (URLs, HTML, XML, CSS, JSON, etc.).

In [11]:
""" you can implicitly define the data type along with array definition.
see the code below ...."""
x = np.array([23, 24.88, 56.9, 78, 97], dtype=np.float16)
x.dtype

dtype('float16')

In [12]:
np.array([1, 2, "3"], dtype=np.float16)

array([1., 2., 3.], dtype=float16)

In [13]:
# this will probably give you an error { the code below }
data_type(np.array(["a", "b", "c", "abc", "vinayak", "hiten"], dtype="complex"))

ValueError: complex() arg is a malformed string

**5. ndarray.itemsize**

In [14]:
import numpy as np

def item_size(my_matrix):
    print("item size: ", my_matrix.itemsize, " bytes")

item_size(np.array([1.34, 2.45, 1.35, 7.69, 8.56]))
item_size(np.array([4j, 4 + 3j, 6 - 9j]))
item_size(np.array(["a", "b", "c"], dtype=np.dtype("U8")))      

item size:  8  bytes
item size:  16  bytes
item size:  32  bytes


## **NumPy Array Creation**
 
There are various functions which we can use to create arrays with the help of numpy library. Following code shows the use of those functions to create a single or multi dimensional array.


In [15]:
import numpy as np
# will print array in the range provided as argument
my_np_arr = np.arange(2, 6)
print(my_np_arr)
print(type(my_np_arr), "\n")
# you can also provide spacing between two intervals by providing third argument
print(np.arange(0, -100, -20))  # output is nothing but numpy.ndarray class object

[2 3 4 5]
<class 'numpy.ndarray'> 

[  0 -20 -40 -60 -80]


In [17]:
my_arr = np.zeros((3, 4), dtype=np.int8)
print(my_arr.dtype)
print(my_arr, type(my_arr))

int8
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]] <class 'numpy.ndarray'>


In [18]:
# will print an array of all zeros
print(np.zeros((2, 3)), "\n")
# will print an array of all ones
print(np.ones((2, 2)), "\n")
# will print a constant array
print(np.full((3, 3), 9999), "\n")
# will print an identity matrix of provided order
print(np.eye(5), "\n")

[[0. 0. 0.]
 [0. 0. 0.]] 

[[1. 1.]
 [1. 1.]] 

[[9999 9999 9999]
 [9999 9999 9999]
 [9999 9999 9999]] 

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]] 



In [18]:
import numpy as np

print(np.eye(5,k=-3), "\n")  # the k argument moves the axis away from diagonal 

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]] 



In [21]:
"""linspace() will create arrays with a specified number of elements, and spaced 
equally between the specified beginning and end values. 
For example: """

print(np.linspace(3, 3.1, 30))

[3.         3.00344828 3.00689655 3.01034483 3.0137931  3.01724138
 3.02068966 3.02413793 3.02758621 3.03103448 3.03448276 3.03793103
 3.04137931 3.04482759 3.04827586 3.05172414 3.05517241 3.05862069
 3.06206897 3.06551724 3.06896552 3.07241379 3.07586207 3.07931034
 3.08275862 3.0862069  3.08965517 3.09310345 3.09655172 3.1       ]


In [23]:
np.pi

3.141592653589793

In [12]:
# you can even perform trigonometry on set of values
# trigonometry funtion accepts angle in radians {2 pi = 360 deg}
vals = np.linspace(0, 2 * np.pi, 20)
print(vals)
print()
print(np.sin(vals))
print()
print(np.cos(vals))
print()
print(np.tan(vals))

[0.         0.33069396 0.66138793 0.99208189 1.32277585 1.65346982
 1.98416378 2.31485774 2.64555171 2.97624567 3.30693964 3.6376336
 3.96832756 4.29902153 4.62971549 4.96040945 5.29110342 5.62179738
 5.95249134 6.28318531]

[ 0.00000000e+00  3.24699469e-01  6.14212713e-01  8.37166478e-01
  9.69400266e-01  9.96584493e-01  9.15773327e-01  7.35723911e-01
  4.75947393e-01  1.64594590e-01 -1.64594590e-01 -4.75947393e-01
 -7.35723911e-01 -9.15773327e-01 -9.96584493e-01 -9.69400266e-01
 -8.37166478e-01 -6.14212713e-01 -3.24699469e-01 -2.44929360e-16]

[ 1.          0.94581724  0.78914051  0.54694816  0.24548549 -0.08257935
 -0.40169542 -0.67728157 -0.87947375 -0.9863613  -0.9863613  -0.87947375
 -0.67728157 -0.40169542 -0.08257935  0.24548549  0.54694816  0.78914051
  0.94581724  1.        ]

[ 0.00000000e+00  3.43300434e-01  7.78331242e-01  1.53061395e+00
  3.94891070e+00 -1.20682053e+01 -2.27977037e+00 -1.08628958e+00
 -5.41172937e-01 -1.66870486e-01  1.66870486e-01  5.41172937e-01
  1.086

## **Random Numbers in NumPy**

### **What is a Random Number?**
Random number does NOT mean a different number every time. Random means something that can not be predicted logically.

### **Pseudo Random and True Random**
Computers work on programs, and programs are definitive set of instructions. So it means there must be some algorithm to generate a random number as well. If there is a program to generate random number it can be predicted, thus it is not truly random.

Random numbers generated through a generation algorithm are called pseudo random.

### **Can we make truly random numbers?**

**Yes**. In order to generate a truly random number on our computers we need to get the random data from some outside source. This outside source is generally our **keystrokes, mouse movements, data on network etc**.

We do not need truly random numbers, unless its related to security (e.g. encryption keys) or the basis of application is the randomness (e.g. Digital roulette wheels).

### **Generate Random Number**
NumPy offers the **random modul**e to work with random numbers.

**1. Generate a random integer from 0 to 100:**

In [26]:
# everything is pseudo random
from numpy import random

x = random.randint(900, 1000)

print(x)

936


**2. The random module's rand() method returns a random float between 0 and 1.**

In [28]:
from numpy import random

x = random.randn(3, 4)  # 3 and 4 are dimensions
x = x.astype(np.float32)

print(x, x.dtype)

[[ 0.28978786  0.5282671   0.7336816  -0.14059608]
 [-1.0600444   0.5619653   2.6050906  -0.31536144]
 [ 1.1824267   0.6669278  -0.47740668 -0.5926983 ]] float32


### **Generate Random Array**
In NumPy we work with arrays, and you can use the two methods from the above examples to make random arrays.

**Integers**

The **randint()** method takes a **size** parameter where you can specify the shape of an array.

In [31]:
from numpy import random

x = random.randint(1000, size=(5, 3))

print(x,'\n\n', x.ndim,'\n', x.shape)

[[157 891 470]
 [ 34 926 517]
 [828 808 707]
 [488 917 577]
 [297 808 242]] 

 2 
 (5, 3)


**Floats**

The **rand()** method also allows you to specify the shape of the array.

**Generate a 1-D array containing 5 random floats:**

In [38]:
from numpy import random

x = random.rand(4)
print(x)

[0.73078121 0.25235012 0.00320035 0.5371335 ]


**Generate a 2-D array with 3 rows, each row containing 5 random numbers:**

In [68]:
from numpy import random

x = random.rand(3, 5)
print(x, x.shape)

[[0.75666865 0.26743861 0.95073569 0.40434748 0.56638469]
 [0.38769396 0.62993852 0.79057891 0.52028045 0.61922357]
 [0.00596853 0.71135718 0.35528642 0.09136865 0.63727383]] (3, 5)


### **Generate Random Number From Array**
The **choice()** method allows you to generate a random value based on an array of values.

The **choice()** method takes an array as a parameter and randomly returns one of the values.

In [33]:
import random
random.choice([1, 2, 3,4,5,6,7,8])

5

In [89]:
from numpy import random

x = random.choice([3, 5, 7, 9, 6373])
print(x)

3


The choice() method also allows you to return an array of values. Add a **size** parameter to specify the shape of the array.

**Generate a 2-D array that consists of the values in the array parameter (3, 5, 7, and 9):**

In [55]:
from numpy import random

x = random.choice([3, 5, 7, 9, 87, 1002], size=(3, 5))
print(x)

[[   5 1002    7    5    3]
 [   9 1002   87 1002    9]
 [  87    3 1002   87 1002]]


### **NumPy Array Indexing**
 
Numpy offers several ways to index into arrays.


In [95]:
import numpy as np

xmat = np.array([[23, 45, 67, 78], [34, 56, 89, 90], [23, 24, 45, 68]])
print(type(xmat))  # will get the class name
print(xmat, "\n")
""" consider the array as a matrix and think about the first term 23 in terms of
x and y position index starting from 0"""

# so to access first term of the matrix we'll write
print(xmat[0, 0])  # 0th row and 0th column

# to access entire matrix let's quickly go through the code below
for i in range(0, 3):
    for j in range(0, 4):
        print(xmat[i, j], end=" ")

<class 'numpy.ndarray'>
[[23 45 67 78]
 [34 56 89 90]
 [23 24 45 68]] 

23
23 45 67 78 34 56 89 90 23 24 45 68 

**Slicing:** Similar to Python lists, numpy arrays can be sliced. Since arrays may be multidimensional, you must specify a slice for each dimension of the array:

In [38]:
import numpy as np

xmat = np.array([[23, 45, 67, 78], [34, 56, 89, 90], [23, 24, 45, 68]])
print(xmat)
print()
# to prxmint first two rows and first two columns
print(xmat[1, 1:], "\n")

temp = xmat[1, 1:]
print(temp.ndim)
# to print entire columns and first row only
print(xmat[:1, :], "\n")

# to print entire rows and first two columns
print(xmat[:, :2])

[[23 45 67 78]
 [34 56 89 90]
 [23 24 45 68]]

[56 89 90] 

1
[[23 45 67 78]] 

[[23 45]
 [34 56]
 [23 24]]


**Note [IMPORTANT]:** You can also mix integer indexing with slice indexing. However, doing so will yield an array of lower rank than the original array.

In [35]:
import numpy as np

xmat = np.array([[23, 45, 67, 78], [34, 56, 89, 90], [23, 24, 45, 68]])
print(f"original mat =>\n{xmat}")
""" there is not only one way to get the second row.
see the code below"""
print(xmat[1, :])
print(xmat[1:2, :])
# then what is the difference??
# see the output correctly you will get to know
# using mixing of integer and slicing as paameter in xmat[]
# yields an array of lower rank while using slicring only
# will give an array of the same rank as the original matrix.
print(xmat[1, :].shape)  # rank = 1
print(xmat[1:2, :].shape)  # rank = 2

original mat =>
[[23 45 67 78]
 [34 56 89 90]
 [23 24 45 68]]
[34 56 89 90]
[[34 56 89 90]]
(4,)
(1, 4)


**Integer array indexing:** When you index into numpy arrays using slicing, the resulting array view will always be a subarray of the original array. In contrast, integer array indexing allows you to construct arbitrary arrays using the data from another array. Here is an example:


In [69]:
a = [1, 2, 3, 3]
b = [1, 4, 9, 4]
c = [2, 3, 4, 5, 6]

for element in zip(a, b, c):
    print(element)

(1, 1, 2)
(2, 4, 3)
(3, 9, 4)
(3, 4, 5)


## NumPy Array Indexing

This code demonstrates integer array indexing in NumPy to access elements of a 2D array.


a = np.array([[1, 4, 5], [2, 3, 6], [4, 7, 9]])
print(a[[0, 1, 2], [0, 1, 2]])  # Prints the diagonal elements

**This is done as the first list i.e [0,1,2] is the row and second one is the column arguments so it is read as 
a[0,0],a[1,1],a[2,2]**

In [40]:
import numpy as np

a = np.array([[1, 4, 5], [2, 3, 6], [4, 7, 9]])
print(a)
# this will print the diagonal elements of the matrix
print(a[[0, 1, 2], [0, 1, 2]])
# The above example of integer array indexing is equivalent to this:
print(np.array([a[0, 0], a[1, 1], a[2, 2]]))  # Prints "[1 3 9]"
# When using integer array indexing, you can reuse the same
# element from the source array:
print(a[[0, 0], [1, 1]])  # Prints "[4 4]"
# Equivalent to the previous integer array indexing example
print(np.array([a[0, 1], a[0, 1]]))  # Prints "[4 4]"
print(a[1,1])

[[1 4 5]
 [2 3 6]
 [4 7 9]]
[1 3 9]
[1 3 9]
[4 4]
[4 4]
3


### **Array Maths**
 
Basic mathematical functions operate elementwise on arrays, and are available both as operator overloads and as functions in the numpy module:


In [81]:
import numpy as np
x = np.array([[1, 2], [3, 4]], dtype=np.float32)
y = np.array([[5, 6], [7, 8]], dtype=np.float64)
# Element Wise sum; both produce the array
# [[ 6.0  8.0]
#  [10.0 12.0]]
print(x + y)
print(np.add(x, y), "\n")
# Element Wise difference; both produce the array
# [[-4.0 -4.0]
#  [-4.0 -4.0]]
print(x - y)
print(np.subtract(x, y), "\n")
# Element Wise product; both produce the array
# [[ 5.0 12.0]
#  [21.0 32.0]]
print(x * y)
print(np.multiply(x, y), "\n")
# Element Wise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y), "\n")
# Element Wise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]] 

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]] 

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]] 

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]] 

[[1.        1.4142135]
 [1.7320508 2.       ]]


**Note:** * is element wise multiplication, not matrix multiplication. We instead use the **dot function** to compute inner products of vectors, to multiply a vector by a matrix, and to multiply matrices. dot is available both as a function in the numpy module and as an instance method of array objects:

In [86]:
import numpy as np

x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])
"""
[1, 2]
[3, 4] 
"""
v = np.array([9, 10])
w = np.array([11, 12])
# print(v.ndim,w.shape)
# print(v, w)
# print(v.shape)
# Inner product of vectors; both produce 219
# vector x vector = scaler value
print(v.dot(w))
print(np.dot(v, w), "\n")  #  dot product :- v*w = v1*w1 + v2*w2
# Matrix / vector product; both produce the rank 1 array [29 67]
# (2, 3) (3,) => (2,)
print(x, v)
print(x.dot(v))
print(np.dot(x, v), "\n")
# Matrix / matrix product; both produce the rank 2 array
# [[19 22]
#  [43 50]]
print(x.dot(y))
print(np.dot(x, y))
# 1d *1d -> scaler value
# 2d * 1d -> 1d
# nd * nd -> matrix

219
219 

[[1 2]
 [3 4]] [ 9 10]
[29 67]
[29 67] 

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


## **Infinix Operator @(Same as np.dot())** 

In [45]:
arr = np.array([[1,2,3],[4,5,6]],dtype="int8")

print(np.dot(arr,arr.T),end='\n\n')
print(arr @ arr.T)

[[14 32]
 [32 77]]

[[14 32]
 [32 77]]


Numpy provides many useful functions for performing computations on arrays; one of the most useful is **sum**:

The function `qr` computes the **QR decomposition** of a matrix. QR decomposition breaks a matrix into two components: 
an orthogonal matrix `Q` and an upper triangular matrix `R`, such that the original matrix can be written as:

\[
A = Q \times R
\]

---

The function `inv` is used to compute the **inverse of a matrix**. It takes a square matrix as input and returns its inverse. 
If the matrix is singular (i.e., it does not have an inverse), an error is raised.

In [13]:
from numpy.linalg import inv,qr
import numpy as np

x = np.array([[1, 2], [3, 4]])

print(np.sum(x))  # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"

print('\n',inv(x),'\n')

Q, R = qr(x)  # QR decomposition of matrix A
print("Q:", Q)
print("R:", R)


10
[4 6]
[3 7]

 [[-2.   1. ]
 [ 1.5 -0.5]] 

Q: [[-0.31622777 -0.9486833 ]
 [-0.9486833   0.31622777]]
R: [[-3.16227766 -4.42718872]
 [ 0.         -0.63245553]]


Apart from computing mathematical functions using arrays, we frequently need to reshape or otherwise manipulate data in arrays. The simplest example of this type of operation is transposing a matrix; to transpose a matrix, simply use the **T** attribute of an array object:


In [6]:
import numpy as np

x = np.array([[1, 2], [3, 4]])
print(x)
# Prints "[[1 2]
#          [3 4]]"
print(x.T)
# Prints "[[1 3]
#          [2 4]]"
# Note that taking the transpose of a rank 1 array does nothing:
v = np.array([1, 2, 3])
print(v)  # Prints "[1 2 3]"
print(v.T)  # Prints "[1 2 3]"

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[1 2 3]
[1 2 3]


In [3]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [48]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

## `np.zeros_like()` Function in NumPy

The `np.zeros_like(arr)` function in NumPy creates a new array filled with zeros that has the **same shape** and **data type** as the given input array `arr`.

### Explanation:

- `arr`: The input array whose shape and data type are to be copied.
- `np.zeros_like(arr)`: Creates an array of zeros that matches the shape and data type of `arr`.

This function is useful when you need to initialize an array for storing results, with the same dimensions as an existing array, but with all elements set to zero.


In [51]:
out = np.zeros_like(arr)
out

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## np.modf(arr)  , arr - ndarry

In [52]:
arr = np.array([1.2, 2.5, -3.7, 4.0])

fractional_parts, integer_parts = np.modf(arr)  

print("Fractional parts:", fractional_parts)
print("Integer parts:", integer_parts)

Fractional parts: [ 0.2  0.5 -0.7  0. ]
Integer parts: [ 1.  2. -3.  4.]


### **Array manipulation routines**

Data manipulation in Python is nearly synonymous with NumPy array manipulation: even newer tools like **Pandas** are built around the NumPy array. We will present several examples of using NumPy array manipulation to **access data and subarrays, and to split, reshape, and join the arrays**. While the types of operations shown here may seem a bit dry and pedantic, they comprise the building blocks of many other examples.

**Example 1:** To copy one array from source to destination you can make use of fucntion 

**numpy.copyto:**

Copies values from one array to another, broadcasting as necessary.

Raises a **TypeError** if the casting rule is violated, and if **where** is provided, it selects which elements to copy.

**where:--** A boolean array which is broadcasted to match the dimensions of destination, and selects elements to **copy from source to destination** wherever it contains the value **True**.

In [123]:
np.array([1, 2, 3]).dtype

dtype('int64')

In [89]:
import numpy as np

my_arr = np.array([1, 3, 4, 7, 8], dtype=np.float32)
my_arr_2 = np.array([2, 4, 6, 78, 89], dtype=np.float64)
# first parameter should be destinbation and second should be source
np.copyto(my_arr_2, my_arr, casting="same_kind")
print(my_arr_2.dtype)
"""
make sure both arrays should have same data types or else it will 
raise an error
and to avoid this kind of error you can set one of the parameter 
provided with 
numpy.copyto and that is casting = 'unsafe'. By default the parameter 
value is 
'same_kind' which means of same data type.
"""

float64


"\nmake sure both arrays should have same data types or else it will \nraise an error\nand to avoid this kind of error you can set one of the parameter \nprovided with \nnumpy.copyto and that is casting = 'unsafe'. By default the parameter \nvalue is \n'same_kind' which means of same data type.\n"

### **Changing Array Shape**

Changing shape of an array plays an important role when you are dealing with multidimensional data, data from images and many more things. There are various ways to change shape of an array and we will see many examples over that.

**1. numpy.reshape: --** Gives a new shape to an array without changing its data.

**2. numpy.ravel: --** Return a contiguous flattened array. A 1-D array, containing the elements of the input, is returned. A copy is made only if needed.

**3. numpy.flatten: --** Return a copy of the array collapsed into one dimension.

**Difference between ravel() and flatten() is -**

ravel() - makes a copy of an array into new memory location and returns it i.e orignal array is not changed.

flatten() - makes a 1D array in place that is it changes the same array.

In [44]:
my_mat = np.array([[34, 1, 2, 4, 5, 6], [56, 45, 7, 89, 654, 54]])
print(my_mat.shape)
# make sure size must be same after performing reshape
np.reshape(my_mat, (3, 4))

(2, 6)


array([[ 34,   1,   2,   4],
       [  5,   6,  56,  45],
       [  7,  89, 654,  54]])

In [45]:
my_flatten = np.ravel(my_mat)
print(my_flatten)

[ 34   1   2   4   5   6  56  45   7  89 654  54]


In [46]:
# here look carefully we need to reference ndarray with flatten function not
# with numpy
t = my_mat.flatten()
print(t)

[ 34   1   2   4   5   6  56  45   7  89 654  54]


### **Transpose-like operations**

**1. numpy.moveaxis:--** Move axes of an array to new positions. Other axes remain in their original order.

**2. numpy.rollaxis:--** Roll the specified axis backwards, until it lies in a given position. This function continues to be supported for backward compatibility, but you should prefer moveaxis.

**3. numpy.swapaxes:--** Interchange two axes of an array.

**Example 3:**

**numpy.moveaxis(a, source, destination)**

In [19]:
x = np.zeros((3, 4, 5, 7, 3))
print(x)

[[[[[0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]
    ...
    [0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]]

   [[0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]
    ...
    [0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]]

   [[0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]
    ...
    [0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]]

   [[0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]
    ...
    [0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]]

   [[0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]
    ...
    [0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]]]


  [[[0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]
    ...
    [0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]]

   [[0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]
    ...
    [0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]]

   [[0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]
    ...
    [0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]]

   [[0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]
    ...
    [0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]]

   [[0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]
    ...
    [0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]]

In [21]:
x1 = np.moveaxis(x, 0, -1)
print(x1.shape)     # thus axis at 0 which has dim=3 moves to last index by shifting others 

(4, 5, 7, 3, 3)


## take this function again with good example

**numpy.rollaxis(a, axis, start=0)**

When **start <= axis**, the axis is rolled back until it lies in this position. When **start > axis**, the axis is rolled until it lies before the mentioned position. The default, 0, results in a “complete” roll.

In [2]:
import numpy as np

a = np.ones((3, 4, 5, 6, 7))
# a

In [99]:
# 3, 4, 5, 6, 7
np.rollaxis(a, 4, 0).shape

(7, 3, 4, 5, 6)

In [103]:
np.rollaxis(a, 2).shape

(5, 3, 4, 6, 7)

In [6]:
# 3 4 5 6 7
np.rollaxis(a, 1, 4).shape

(3, 5, 6, 4, 7)

In [11]:
a = np.ones((3, 4, 5, 6, 7, 5, 3, 4, 5, 2))
# a
np.rollaxis(a,2,8).shape

(3, 4, 6, 7, 5, 3, 4, 5, 5, 2)

**numpy.swapaxes(a, axis1, axis2)**

In [105]:
x = np.array([[1, 2, 3]])
print(x.shape)

x_swapped = np.swapaxes(x, 0, 1)
print(x_swapped)
print(x_swapped.shape)

(1, 3)
[[1]
 [2]
 [3]]
(3, 1)


In [12]:
x = np.zeros((3, 3, 4))
x.swapaxes(0, 2).shape

(4, 3, 3)

### **Joining arrays**

**1. numpy.concatenate:--** Join a sequence of arrays along an existing axis.

**2. numpy.stack:--** Join a sequence of arrays along a new axis. The axis parameter specifies the index of the new axis in the dimensions of the result. For example, if axis=0 it will be the first dimension and if axis=-1 it will be the last dimension. hstack, vsrtack, dstack many more are there which works in the same way stack does. For more info, you can search on google.

**Example 4:**

**numpy.concatenate((a1, a2, ...), axis=0, out=None)**

out: If provided, the destination to place the result

In [16]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

print(a.shape, b.shape)
np.concatenate((a, b), axis=0)  # all the input array dimensions except for the concatenation axis must match exactly

(2, 2) (1, 2)


array([[1, 2],
       [3, 4],
       [5, 6]])

In [57]:
b, b.T

(array([[5, 6]]),
 array([[5],
        [6]]))

In [18]:
np.concatenate((a, b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

**numpy.stack(arrays, axis=0, out=None)**

In [59]:
[x * x for x in range(10)]  # -> [0, 1, 2 3, ..., 9]  - List Comprehension

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [20]:
arrays = np.array([np.random.rand(3, 4) for i in range(10)])
arrays.shape

(10, 3, 4)

In [26]:
np.stack((arrays, arrays, arrays), axis=3).shape

(10, 3, 4, 3)

In [23]:
out1 = np.stack(arrays, axis=1) 
print(out1.shape)
print(np.stack(arrays, axis=2).shape)

(3, 10, 4)
(3, 4, 10)


In [27]:
# print(np.stack(arrays, axis=2))
print()
print(np.stack(arrays, axis=2).shape)


(3, 4, 10)


### **Adding and removing elements**

**1. numpy.delete:--** Return a new array with sub-arrays along an axis deleted. For a one dimensional array, this returns those entries not returned by arr[obj].

**2. numpy.insert:--** Insert values along the given axis before the given indices.

**3. numpy.append:--** Append values to the end of an array.

**Example 5:**

**numpy.delete(arr, obj, axis=None)**

axis: The axis along which to delete the subarray defined by obj. If axis is None, obj is applied to the flattened array.

In [29]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [31]:
np.delete(arr, 1, 1) 

array([[ 1,  3,  4],
       [ 5,  7,  8],
       [ 9, 11, 12]])

In [32]:
np.delete(arr, 1, 0) 

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

**numpy.insert(arr, obj, values, axis=None)**

axis: Axis along which to insert values. If axis is None then arr is flattened first.



In [35]:
a = np.array([[1, 1], [2, 2], [3, 3]])
a

array([[1, 1],
       [2, 2],
       [3, 3]])

In [78]:
np.insert(a, 1, 5)

array([1, 5, 1, 2, 2, 3, 3])

In [36]:
np.insert(a, 1, 5, axis=0)

array([[1, 1],
       [5, 5],
       [2, 2],
       [3, 3]])

In [48]:
np.insert(a, [1], [[1], [2], [3]], axis=1) 

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [49]:
np.insert(a, [1], [[1], [2], [3]], axis=0)  # this time it has entered at index 1 in the orignal ndarray
# i.e - array([[1, 1],
#               inserted here
#              [2, 2],
#              [3, 3]]) 


array([[1, 1],
       [1, 1],
       [2, 2],
       [3, 3],
       [2, 2],
       [3, 3]])

In [46]:
np.insert(a, 0, [[1], [2], [3]], axis=1) 
# this means that at index 0 and axis 1 columwise the array [1,2,3] is added
# i.e - array([[inserted here,1, 1],
#              [inserted here,2, 2],
#              [inserted here,3, 3]]) 

array([[1, 2, 3, 1, 1],
       [1, 2, 3, 2, 2],
       [1, 2, 3, 3, 3]])

**numpy.append(arr, values, axis=None)**

In [51]:
x = [[1, 2, 3], [4, 5, 6]]
np.append(x, [[7, 8, 9]], axis=0)           # here  [[7, 8, 9]] is a 2D array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [56]:
np.append([[1, 2, 3], [4, 5, 6]], [7, 8, 9], axis=0)        # here  [[7, 8, 9]] is not a 2D array

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

### **NumPy Linear Algebra**

The Linear Algebra module of NumPy offers various methods to apply linear algebra on any numpy array.

**One can find:**

- rank, determinant, trace, etc. of an array.
- eigen values of matrices
- matrix and vector products (dot, inner, outer,etc. product), matrix exponentiation
- solve linear or tensor equations and much more!

#### **Matrix and vector products**

**1. numpy.dot:--** Dot product of two arrays.

**2. numpy.linalg.multi_dot:--** Compute the dot product of two or more arrays in a single function call, while automatically selecting the fastest evaluation order.

**3. numpy.vdot:--** Return the dot product of two vectors.

**4. numpy.inner:--** Inner product of two arrays. Ordinary inner product of vectors for 1-D arrays (without complex conjugation), in higher dimensions a sum product over the last axes.

**5. numpy.outer:--** Compute the outer product of two vectors.

Given two vectors, **a = [a0, a1, ..., aM]** and **b = [b0, b1, ..., bN]**, the outer product is:

```
[[a0*b0  a0*b1 ... a0*bN ]
 [a1*b0    .
 [ ...          .
 [aM*b0            aM*bN ]]
```

**6. numpy.matmul:--** Matrix product of two arrays.

**Example 1:**


**numpy.dot(a, b, out=None)**

Raises
**ValueError**
If the last dimension of a is not the same size as the second-to-last dimension of b.

In [51]:
print(np.dot(3, 4))
print(np.dot([2j, 3j], [2j, 3j]))

12
(-13+0j)


In [ ]:
a = [[1, 0], [0, 1]]
b = [[4, 1], [2, 2]]
np.dot(a, b)            # matrix multiplication

array([[4, 1],
       [2, 2]])

In [ ]:
a = np.arange(3 * 4 * 5 * 6).reshape((3, 4, 5, 6))
b = np.arange(3 * 4 * 5 * 6)[::-1].reshape((5, 4, 6, 3))
np.dot(a, b)[2, 3, 2, 1, 2, 2]

499128

**numpy.linalg.multi_dot(arrays, \*, out=None)**

In [ ]:
from numpy.linalg import multi_dot

# Prepare some data
A = np.random.random((20, 10))
B = np.random.random((10, 7))
C = np.random.random((7, 5))
D = np.random.random((5, 2))

# the actual dot multiplication
result = multi_dot([A, B, C, D])
print(result)

[[12.85374252 12.20401372]
 [11.64124774 10.59212751]
 [13.302321   12.20176738]
 [19.28583961 18.15756699]
 [12.43842326 11.72216202]
 [11.14629548 10.53758116]
 [15.5870099  14.31361718]
 [15.80357178 14.9643075 ]
 [10.2580188   9.74914945]
 [14.0233273  13.13021458]
 [21.87406391 20.44635352]
 [13.48428733 12.79386603]
 [13.38791439 12.78480835]
 [12.11807492 11.1173885 ]
 [12.79009684 11.71355608]
 [13.9657519  12.92346626]
 [12.36971695 11.56585   ]
 [11.79005939 10.69542239]
 [17.15709732 15.76261881]
 [11.66723865 10.84897081]]


**numpy.vdot(a, b)**

# Hermitian Dot Product with `np.vdot()`

The Hermitian dot product, computed using `np.vdot(a, b)`, involves conjugating the first vector before performing the dot product with the second vector.

## Solution - 

a = [1 + 2j, 3 + 4j] 
b = [5 + 6j, 7 + 8j]

conjugate  a = [1 - 2j, 3 - 4j] 

conjugate  b = [5 - 6j, 7 - 8j]


(1−2j)(5+6j)+(3−4j)(7+8j) 

1st = (1−2j)(5+6j)=5+6j−10j+12=17−4j

2nd = (3−4j)(7+8j)=21+24j−28j+32=53−4j

= (−7−4j)+(−11−4j)= 70−8j

In [58]:
a = np.array([1 + 2j, 3 + 4j])
b = np.array([5 + 6j, 7 + 8j])
np.vdot(a, b)

np.complex128(70-8j)

In [ ]:
a = np.array([[1, 4], [5, 6]])
b = np.array([[4, 1], [2, 2]])
np.vdot(a, b)

30

**numpy.inner(a, b)**

out.shape = a.shape[:-1] + b.shape[:-1]

In [53]:
a = np.array([1, 2, 3])
print(a.shape)
b = np.array([0, 1, 0])
print(b.shape)
res = np.inner(a, b)
print(res, res.shape)

(3,)
(3,)
2 ()


In [ ]:
a = np.arange(12).reshape((2, 3, 2))
print(a)
print()

b = np.arange(2)
print(b)
print()

print(np.inner(a, b))

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]

[0 1]

[[ 1  3  5]
 [ 7  9 11]]


**numpy.outer(a, b)**

In [ ]:
np.outer(np.ones((5,)), np.linspace(-2, 2, 5))

array([[-2., -1.,  0.,  1.,  2.],
       [-2., -1.,  0.,  1.,  2.],
       [-2., -1.,  0.,  1.,  2.],
       [-2., -1.,  0.,  1.,  2.],
       [-2., -1.,  0.,  1.,  2.]])

**numpy.matmul**

**ValueError**
If the last dimension of a is not the same size as the second-to-last dimension of b.

In [ ]:
a = np.ones([9, 5, 7, 4])
c = np.ones([9, 5, 4, 3])
np.dot(a, c).shape

(9, 5, 7, 9, 5, 3)

In [ ]:
a = np.array([[1, 0], [0, 1]])
b = np.array([[4, 1], [2, 2]])
np.matmul(a, b)

array([[4, 1],
       [2, 2]])

### **Matrix eigenvalues**

**1. numpy.linalg.eig:--** Compute the eigenvalues and right eigenvectors of a square array.

**2. numpy.linalg.eigh:--** Return the eigenvalues and eigenvectors of a complex Hermitian (conjugate symmetric) or a real symmetric matrix. Returns two objects, a 1-D array containing the eigenvalues of a, and a 2-D square array or matrix (depending on the input type) of the corresponding eigenvectors (in columns).

**3. numpy.linalg.eigvals:--** 	Compute the eigenvalues of a general matrix.

**4. numpy.linalg.eigvalsh:--** Compute the eigenvalues of a complex Hermitian or real symmetric matrix.

**Example 2:**

**numpy.linalg.eig(a)**

In [ ]:
from numpy import linalg as la

a = np.random.randn(2, 2)
print(a, "\n")
eigen_vals, eigen_vects = la.eig(a)

print(eigen_vals)
print()
print(eigen_vects)

[[ 0.63873273  2.08129531]
 [-0.13162044  0.91463705]] 

[0.77668489+0.50488634j 0.77668489-0.50488634j]

[[0.96980499+0.j         0.96980499-0.j        ]
 [0.06428049+0.23525796j 0.06428049-0.23525796j]]


**numpy.linalg.eigh(a)**

In [ ]:
from numpy import linalg as la

a = np.array([[1, -2j], [2j, 5]])
print(a, "\n")
eigen_vals, eigen_vects = la.eigh(a)

print(eigen_vals)
print()
print(eigen_vects)

[[ 1.+0.j -0.-2.j]
 [ 0.+2.j  5.+0.j]] 

[0.17157288 5.82842712]

[[-0.92387953+0.j         -0.38268343+0.j        ]
 [ 0.        +0.38268343j  0.        -0.92387953j]]


**numpy.linalg.eigvals(a)**

Main difference between eigvals and eig: the eigenvectors aren’t returned.

In [ ]:
a = np.random.randn(2, 2)
print(a, "\n")
la.eigvals(a)

[[-0.06227234 -0.36712736]
 [ 1.62956979  0.15919536]] 



array([0.04846151+0.76550484j, 0.04846151-0.76550484j])

**numpy.linalg.eigvalsh(a)**

Main difference from eigh: the eigenvectors are not computed.

In [ ]:
a = np.array([[1, -2j], [2j, 5]])
print(a, "\n")
la.eigvalsh(a)

[[ 1.+0.j -0.-2.j]
 [ 0.+2.j  5.+0.j]] 



array([0.17157288, 5.82842712])

# Matrix and Vector Multiplications

## 1. Matrix * Matrix = Matrix
- When two matrices are multiplied together, the result is a matrix.
- Matrix multiplication requires that the number of columns in the first matrix is equal to the number of rows in the second matrix.
- The resulting matrix has the same number of rows as the first matrix and the same number of columns as the second matrix.

## 2. Vector * Matrix = Vector
- Multiplying a vector by a matrix results in a vector.
- The vector's dimension must match the number of columns (or rows if it's a row vector) of the matrix.
- The result is a vector whose length corresponds to the number of columns in the matrix.

## 3. Vector * Vector = Scalar
- The multiplication of two vectors results in a scalar.
- This operation is known as the dot product and is the sum of the products of corresponding components from both vectors.


In [59]:
# Matrix * Matrix
import numpy as np

A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])
C = np.dot(A, B)  # or A @ B
print("Matrix C:\n", C)

Matrix C:
 [[19 22]
 [43 50]]


In [60]:
# Matrix * Vector
v = np.array([1, 2])
M = np.array([[3, 4],[5, 6]])
R = np.dot(v, M)
print("Resulting Vector R:", R)

Resulting Vector R: [13 16]


In [61]:
# Vector* Vector
u = np.array([1, 2, 3])
v = np.array([4, 5, 6])
scalar_result = np.dot(u, v)
print("Scalar Result:", scalar_result)

Scalar Result: 32


# **Quartiles** using Numpy

In [5]:
import numpy as np

data = [80, 94, 97, 105, 107, 112, 116, 116, 118, 119, 120, 127, 128, 138, 138, 139, 142, 143, 144, 145, 150, 162, 171, 172]
Q1 = np.percentile(data, 25)  # First quartile
Q2 = np.percentile(data, 50)  # Median
Q3 = np.percentile(data, 75)  # Third quartile

print(Q1,Q2,Q3,np.percentile(data, 20),np.percentile(data, 47),np.percentile(data, 83),sep='\t')

115.0	127.5	143.25	110.0	125.66999999999999	145.45


## **Basics of Variance**

A company produces a lightweight valve that is specified to weigh 1365 grams.
Unfortunately, because of imperfections in the manufacturing process not all of the
valves produced weigh exactly 1365 grams. In fact, the weights of the valves produced are normally distributed with a mean weight of 1365 grams and a standard
deviation of 294 grams. Within what range of weights would approximately 95% of
the valve weights fall? Approximately 16% of the weights would be more than what
value? Approximately 0.15% of the weights would be less than what value?
Solution

Because the valve weights are normally distributed, the empirical rule applies.
According to the empirical rule, approximately 95% of the weights should fall within
2 = 1365 2(294) = 1365 588. Thus, approximately 95% should fall between
777 and 1953. Approximately 68% of the weights should fall within 1 , and 32%
should fall outside this interval. Because the normal distribution is symmetrical,
approximately 16% should lie above + 1 = 1365 + 294 = 1659. Approximately 99.7%
of the weights should fall within 3 , and .3% should fall outside this interval. Half
of these, or .15%, should lie below m - 3s = 1365 - 3(294) = 1365 - 882 = 483.

### **Summary:**

Not just linear algebra but many mathematical operations we can perfrom using numpy library and we have studied the way numpy computes the array, creates the array, manipulates the shape, performs mathematical operations on it. After this whenever new concepts will come we will learn more about numpy library contents so that we will better understand where to use what.